extends: 'plugin:react/recommended'
parserOptions:
  ecmaFeatures:
    jsx: true
rules:
  react/jsx-first-prop-new-line:
    - multiline
  react/jsx-closing-bracket-location:
    - 2
    - tag-aligned
  react/prop-types: off
  react/jsx-key: off
